### ISSUE TITLE
Is it working together with the midi plugin from Epic

### ISSUE THREAD

**Issue by NNois** [Geromatic/Midi-Unreal#18]
Hi,
How exactly this plugin works with the midi from epic ?
Could you explain briefly what's the difference ?

I see one for now yours can send to the midi device while the epic one can receive only, are you complementary? do I need to disable the epic one ?

**Comment by Geromatic** [comment]
I never thought of how it worked with the built one. You can think of is as complementary,  this was created as a class project and I decided to just give it to the mass.

You are able to load MIDI files and be able to play and use their data as well as transmit/receive MIDI device data .  I do not want to judge they basically are the same in terms of receiving MIDI device data .  All mine is just to provide full MIDI capability to the user rather than have limitations (although their are some ex. documentation, certain blueprint functionality, etc). 

This may be repeat but my Idea was to allow a game engine more power by giving more options to people rather than to just game developers and allow anyone to use/modify the code free of charge.

You don't have to disable the EPIC version since it doesn't conflict with plugin.  It just the user to decide which preference on how they want to receive MIDI device data.

Note: the only reason it was called "procedural" MIDI was because I thought Epic didn't want generic names so I tossed in simple sin wave function and called it "Procedural". funny aha

I apologize if I went to heart out on this.
